spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Nexos?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
    username: root
    password: Ryou.2003
  jpa:
    show-sql: true